/** Proposal-aligned roles. `teacher` kept for backward compatibility; prefer `doctor`. */
const ROLES = {
  SUPER_ADMIN: 'super_admin',
  INSTRUCTOR: 'instructor',
  TEACHER: 'teacher',
  DOCTOR: 'doctor',
  ASSISTANT: 'assistant',
  STUDENT: 'student',
};

const ALL_ROLES = Object.values(ROLES);

const COURSE_OWNERS = [ROLES.INSTRUCTOR, ROLES.TEACHER, ROLES.DOCTOR];

const COURSE_CREATORS = [ROLES.SUPER_ADMIN, ROLES.INSTRUCTOR, ROLES.TEACHER, ROLES.DOCTOR];

const CONTENT_STAFF = [ROLES.SUPER_ADMIN, ROLES.INSTRUCTOR, ROLES.TEACHER, ROLES.DOCTOR, ROLES.ASSISTANT];

const STAFF_AND_STUDENT = [...CONTENT_STAFF, ROLES.STUDENT];

const LIVE_HOSTS = [ROLES.INSTRUCTOR, ROLES.TEACHER, ROLES.DOCTOR, ROLES.ASSISTANT];

const WHATSAPP_SENDERS = [ROLES.SUPER_ADMIN, ROLES.INSTRUCTOR];

const PLATFORM_STUDENT_VIEWERS = [ROLES.SUPER_ADMIN, ROLES.INSTRUCTOR];

function isDoctorLike(role) {
  return role === ROLES.TEACHER || role === ROLES.DOCTOR;
}

module.exports = {
  ROLES,
  ALL_ROLES,
  COURSE_OWNERS,
  COURSE_CREATORS,
  CONTENT_STAFF,
  STAFF_AND_STUDENT,
  LIVE_HOSTS,
  WHATSAPP_SENDERS,
  PLATFORM_STUDENT_VIEWERS,
  isDoctorLike,
};
